# Generated by Django 4.2.23 on 2025-10-04 16:45

import book.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('studies', 'Studies'), ('novel', 'Novel'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('history', 'History'), ('science', 'Science'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('comics', 'Comics'), ('children', 'Children'), ('religion', 'Religion'), ('philosophy', 'Philosophy'), ('romance', 'Romance'), ('horror', 'Horror')], default='science', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', validators=[book.models.Book.validate_image])),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='book_pdfs/', validators=[book.models.Book.validate_pdf])),
                ('book_online', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('stock', models.BooleanField(default=True)),
                ('total_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author')),
            ],
        ),
    ]
