# Generated by Django 5.2.6 on 2025-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_description_book_rating_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('studies', 'Studies'), ('novel', 'Novel'), ('poetry', 'Poetry'), ('drama', 'Drama'), ('history', 'History'), ('science', 'Science'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('comics', 'Comics'), ('children', 'Children'), ('religion', 'Religion'), ('philosophy', 'Philosophy'), ('romance', 'Romance'), ('horror', 'Horror'), ('research paper', 'research_paper')], default='science', max_length=50),
        ),
    ]
