# Generated by Django 5.2.6 on 2025-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
