# Generated by Django 4.2.23 on 2025-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_book_online_book_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
