# Generated by Django 4.2.23 on 2025-09-17 14:45

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/', validators=[book.models.Book.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', validators=[book.models.Book.validate_image]),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
