# Generated by Django 4.2.23 on 2025-09-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_total_stock_alter_book_book_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
