# Generated by Django 4.2.23 on 2025-10-04 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import research.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True, max_length=2000)),
                ('field', models.CharField(choices=[('cs', 'Computer Science'), ('medicine', 'Medicine'), ('engineering', 'Engineering'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('mathematics', 'Mathematics'), ('social_science', 'Social Science'), ('other', 'Other')], default='other', max_length=50)),
                ('research_pdf', models.FileField(blank=True, null=True, upload_to='research_papers/', validators=[research.models.validate_pdf])),
                ('publication_date', models.DateField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('citations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='research.author')),
            ],
        ),
    ]
