# Generated by Django 4.2.23 on 2025-09-17 16:09

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='research_pdf',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/', validators=[research.models.validate_pdf]),
        ),
    ]
